#Requires -Version 7
<#
.SYNOPSIS
    Generates native host adapters from the canonical AI assets.

.DESCRIPTION
    Canonical instructions live under .ai/instructions with portable `paths`
    metadata. This script renders the native path-scoped representations used by:
      - GitHub Copilot: .github/instructions/<name>.instructions.md (`applyTo`)
      - Claude Code:    .claude/rules/<name>.md (`paths`)

    Claude Code also only natively discovers:
      - Skills:        .claude/skills/<name>/SKILL.md
      - Subagents:     .claude/agents/<name>.md
      - Slash commands: .claude/commands/<name>.md

    The canonical repository assets live in .agents/skills/ (shared skill
    library) and .ai/ (agents, prompts). This script generates thin redirect
    wrappers so Claude Code auto-triggers skills, can spawn selected agent
    roles as subagents, and exposes prompts as slash commands — without
    duplicating canonical content.

    The script is idempotent: it first removes previously generated wrappers
    (identified by the generation marker) and then regenerates everything.
    Hand-authored files under .claude/ without the marker are never touched.

.NOTES
    Re-run after adding, renaming, or removing anything under .ai/instructions/,
    .agents/skills/, .ai/agents/, or .ai/prompts/.
#>
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$RepoRoot = $PSScriptRoot

$Marker = 'Generated by sync_ai_assets.ps1 - do not edit. Edit the canonical source and re-run the script.'
$LegacyMarker = 'Generated by sync_claude_assets.ps1 - do not edit. Edit the canonical source and re-run the script.'
$PriorPublicMarker = 'Generated by sync_ai_assets.ps1 - do not edit.'

$InstructionsRoot = Join-Path $RepoRoot '.ai/instructions'
$SharedSkillsRoot = Join-Path $RepoRoot '.agents/skills'
$PromptsRoot      = Join-Path $RepoRoot '.ai/prompts'
$CopilotRules     = Join-Path $RepoRoot '.github/instructions'
$ClaudeRules      = Join-Path $RepoRoot '.claude/rules'
$ClaudeSkills     = Join-Path $RepoRoot '.claude/skills'
$ClaudeAgents     = Join-Path $RepoRoot '.claude/agents'
$ClaudeCommands   = Join-Path $RepoRoot '.claude/commands'

# Agent roles promoted to native Claude Code subagents. Keep this list small:
# every entry adds its description to Claude's context in each session.
# Descriptions are delegation-oriented ("use when...") on purpose.
$AgentRoles = @(
    @{ Slug = 'qa-automation';          Source = '.ai/agents/qa-automation.agent.md'
       Description = 'QA automation role for this repository. Use to plan and execute test passes across the System Uptime Tracker solution, its web client, and container-backed local services.' }
    @{ Slug = 'debug';                  Source = '.ai/agents/debug.agent.md'
       Description = 'Systematic debugging role. Use to reproduce, isolate, and fix a reported bug end-to-end following the repository debugging workflow.' }
    @{ Slug = 'playwright-tester';      Source = '.ai/agents/playwright-tester.agent.md'
       Description = 'Playwright end-to-end testing role. Use to write, run, and repair Playwright browser tests for this repository.' }
    @{ Slug = 'terraform-iac-reviewer'; Source = '.ai/agents/terraform-iac-reviewer.agent.md'
       Description = 'Terraform infrastructure-as-code review role. Use to review Terraform changes for state safety, least privilege, module patterns, and plan/apply discipline.' }
)

function Get-FrontMatterLines {
    param([string]$Path)
    $lines = Get-Content -Path $Path
    if ($lines.Count -lt 3 -or $lines[0] -notmatch '^---\s*$') { return $null }
    for ($i = 1; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -match '^---\s*$') { return $lines[1..($i - 1)] }
    }
    return $null
}

function Get-SingleLineDescription {
    param([string[]]$FrontMatter)
    foreach ($line in $FrontMatter) {
        if ($line -match "^description:\s*(.+)$") {
            return $Matches[1].Trim().Trim("'").Trim('"')
        }
    }
    return $null
}

function Get-FrontMatterFieldValues {
    param(
        [string[]]$FrontMatter,
        [string]$Name
    )

    $values = @()
    for ($i = 0; $i -lt $FrontMatter.Count; $i++) {
        if ($FrontMatter[$i] -notmatch "^$([regex]::Escape($Name)):\s*(.*)$") {
            continue
        }

        $inlineValue = $Matches[1].Trim()
        if ($inlineValue) {
            $inlineValue = $inlineValue.Trim("'").Trim('"')
            return @($inlineValue)
        }

        for ($j = $i + 1; $j -lt $FrontMatter.Count; $j++) {
            if ($FrontMatter[$j] -match '^\s+-\s+(.+)$') {
                $values += $Matches[1].Trim().Trim("'").Trim('"')
                continue
            }
            break
        }
        return $values
    }

    return $values
}

function Get-FrontMatterFieldLine {
    param(
        [string[]]$FrontMatter,
        [string]$Name
    )

    return $FrontMatter | Where-Object { $_ -match "^$([regex]::Escape($Name)):" } | Select-Object -First 1
}

function Get-MarkdownBody {
    param([string]$Path)

    $lines = Get-Content -Path $Path
    if ($lines.Count -lt 3 -or $lines[0] -notmatch '^---\s*$') {
        return $lines -join "`n"
    }

    for ($i = 1; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -match '^---\s*$') {
            $bodyStart = $i + 1
            while ($bodyStart -lt $lines.Count -and -not $lines[$bodyStart].Trim()) {
                $bodyStart++
            }
            if ($bodyStart -ge $lines.Count) { return '' }
            return $lines[$bodyStart..($lines.Count - 1)] -join "`n"
        }
    }

    return $lines -join "`n"
}

function Remove-GeneratedWrappers {
    param([string]$Root, [string]$Filter)
    if (-not (Test-Path $Root)) { return }
    foreach ($file in Get-ChildItem -Path $Root -Recurse -Filter $Filter -File) {
        $content = Get-Content -Path $file.FullName -Raw
        if ($content -match [regex]::Escape($Marker) -or
            $content -match [regex]::Escape($LegacyMarker) -or
            $content -match [regex]::Escape($PriorPublicMarker)) {
            if ($file.Name -eq 'SKILL.md') {
                Remove-Item -Path $file.Directory.FullName -Recurse -Force
            } else {
                Remove-Item -Path $file.FullName -Force
            }
        }
    }
}

# --- Clean previously generated wrappers -------------------------------------
Remove-GeneratedWrappers -Root $CopilotRules  -Filter '*.instructions.md'
Remove-GeneratedWrappers -Root $ClaudeRules   -Filter '*.md'
Remove-GeneratedWrappers -Root $ClaudeSkills   -Filter 'SKILL.md'
Remove-GeneratedWrappers -Root $ClaudeAgents   -Filter '*.md'
Remove-GeneratedWrappers -Root $ClaudeCommands -Filter '*.md'

# --- Instructions: canonical rules -> Copilot and Claude scoped adapters -----
$instructionCount = 0
foreach ($file in Get-ChildItem -Path $InstructionsRoot -Filter '*.md' -File | Sort-Object Name) {
    $frontMatter = Get-FrontMatterLines -Path $file.FullName
    if (-not $frontMatter) {
        Write-Warning "Skipping instruction '$($file.Name)': no YAML frontmatter."
        continue
    }

    $paths = @(Get-FrontMatterFieldValues -FrontMatter $frontMatter -Name 'paths')
    if ($paths.Count -eq 0) {
        Write-Warning "Skipping instruction '$($file.Name)': no portable paths metadata."
        continue
    }

    $slug = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
    $descriptionLine = Get-FrontMatterFieldLine -FrontMatter $frontMatter -Name 'description'
    $excludeAgentsLine = Get-FrontMatterFieldLine -FrontMatter $frontMatter -Name 'excludeAgents'
    $body = Get-MarkdownBody -Path $file.FullName
    $relSource = ".ai/instructions/$($file.Name)"

    $copilotFrontMatter = @()
    if ($descriptionLine) { $copilotFrontMatter += $descriptionLine }
    $copilotPatterns = ($paths | ForEach-Object { $_ -replace "'", "''" }) -join ','
    $copilotFrontMatter += "applyTo: '$copilotPatterns'"
    if ($excludeAgentsLine) {
        $copilotFrontMatter += $excludeAgentsLine -replace '^excludeAgents:', 'excludeAgent:'
    }

    $copilotContent = @(
        '---'
        $copilotFrontMatter
        '---'
        ''
        "<!-- $Marker -->"
        "<!-- Canonical source: $relSource -->"
        ''
        $body
    ) -join "`n"

    $copilotFile = Join-Path $CopilotRules "$slug.instructions.md"
    if (Test-Path $copilotFile) {
        Write-Warning "Skipping Copilot instruction '$slug': hand-authored adapter already exists."
    } else {
        New-Item -ItemType Directory -Force -Path $CopilotRules | Out-Null
        Set-Content -Path $copilotFile -Value $copilotContent -NoNewline
    }

    $claudeFrontMatter = @()
    if ($descriptionLine) { $claudeFrontMatter += $descriptionLine }
    $claudeFrontMatter += 'paths:'
    $claudeFrontMatter += $paths | ForEach-Object { "  - '$($_ -replace "'", "''")'" }

    $claudeContent = @(
        '---'
        $claudeFrontMatter
        '---'
        ''
        "<!-- $Marker -->"
        "<!-- Canonical source: $relSource -->"
        ''
        $body
    ) -join "`n"

    $claudeFile = Join-Path $ClaudeRules "$slug.md"
    if (Test-Path $claudeFile) {
        Write-Warning "Skipping Claude rule '$slug': hand-authored adapter already exists."
    } else {
        New-Item -ItemType Directory -Force -Path $ClaudeRules | Out-Null
        Set-Content -Path $claudeFile -Value $claudeContent -NoNewline
    }

    $instructionCount++
}

# --- Skills: .agents/skills/<name>/SKILL.md -> .claude/skills/<name>/SKILL.md
$skillCount = 0
foreach ($dir in Get-ChildItem -Path $SharedSkillsRoot -Directory | Sort-Object Name) {
    $source = Join-Path $dir.FullName 'SKILL.md'
    if (-not (Test-Path $source)) { continue }

    $slug = $dir.Name
    $target = Join-Path $ClaudeSkills $slug
    $targetFile = Join-Path $target 'SKILL.md'
    if (Test-Path $targetFile) {
        Write-Warning "Skipping skill '$slug': hand-authored Claude skill already exists."
        continue
    }

    $fm = Get-FrontMatterLines -Path $source
    if (-not $fm) {
        Write-Warning "Skipping skill '$slug': no YAML frontmatter in $source."
        continue
    }

    # Force the name to the directory slug and make sure a redirect wrapper can
    # always read its canonical source when the skill restricts tools.
    $fm = @($fm | Where-Object { $_ -notmatch '^name:' })
    $fm = $fm | ForEach-Object {
        if ($_ -match '^allowed-tools:' -and $_ -notmatch '(?i)\bread\b') {
            if ($_ -match '^allowed-tools:\s*\[(.*)\]\s*$') {
                "allowed-tools: [$($Matches[1]), 'Read']"
            } else {
                "$_, Read"
            }
        } else { $_ }
    }
    $fm = @("name: $slug") + $fm

    $relSource = ".agents/skills/$slug/SKILL.md"
    $content = @(
        '---'
        $fm
        '---'
        ''
        "<!-- $Marker -->"
        ''
        'This is a Claude Code discovery wrapper for a shared repository skill.'
        "Read and follow the canonical skill at ``$relSource``,"
        'resolving its `references/`, `scripts/`, `assets/`, and `agents/`'
        'resources relative to that canonical directory, not this wrapper.'
    ) -join "`n"

    New-Item -ItemType Directory -Force -Path $target | Out-Null
    Set-Content -Path $targetFile -Value $content -NoNewline
    $skillCount++
}

# --- Agents: selected .ai/agents/*.agent.md -> .claude/agents/<slug>.md ------
$agentCount = 0
foreach ($role in $AgentRoles) {
    $source = Join-Path $RepoRoot $role.Source
    if (-not (Test-Path $source)) {
        Write-Warning "Skipping agent '$($role.Slug)': source $($role.Source) not found."
        continue
    }
    $targetFile = Join-Path $ClaudeAgents "$($role.Slug).md"
    if (Test-Path $targetFile) {
        Write-Warning "Skipping agent '$($role.Slug)': hand-authored subagent already exists."
        continue
    }

    $content = @(
        '---'
        "name: $($role.Slug)"
        "description: $($role.Description)"
        '---'
        ''
        "<!-- $Marker -->"
        ''
        "Adopt the role defined in ``$($role.Source)``. Read that file completely"
        'before doing anything else, then follow `AGENTS.md` and'
        '`.ai/constitution.md`. Ignore tool or model names in the role file'
        'frontmatter; they target other AI tools. Use your normally available'
        'tools, and report concrete results (files changed, commands run, test'
        'output) back to the caller.'
    ) -join "`n"

    New-Item -ItemType Directory -Force -Path $ClaudeAgents | Out-Null
    Set-Content -Path $targetFile -Value $content -NoNewline
    $agentCount++
}

# --- Commands: .ai/prompts/*.prompt.md -> .claude/commands/<slug>.md ----------
# Skipped when a same-named skill exists: the skill already provides /<name>
# invocation, and duplicate names would be ambiguous.
$commandCount = 0
$skippedCommands = @()
foreach ($file in Get-ChildItem -Path $PromptsRoot -Filter '*.prompt.md' -File | Sort-Object Name) {
    $slug = ($file.Name -replace '\.prompt\.md$', '').ToLowerInvariant()

    if (Test-Path (Join-Path $ClaudeSkills "$slug/SKILL.md")) {
        $skippedCommands += $slug
        continue
    }
    $targetFile = Join-Path $ClaudeCommands "$slug.md"
    if (Test-Path $targetFile) {
        Write-Warning "Skipping command '$slug': hand-authored command already exists."
        continue
    }

    $fm = Get-FrontMatterLines -Path $file.FullName
    $description = if ($fm) { Get-SingleLineDescription -FrontMatter $fm } else { $null }
    if (-not $description) { $description = "Run the $slug workflow from .ai/prompts/." }
    if ($description.Length -gt 1024) { $description = $description.Substring(0, 1021) + '...' }

    $relSource = ".ai/prompts/$($file.Name)"
    $content = @(
        '---'
        "description: '$($description -replace ""'"", ""''"")'"
        '---'
        ''
        "<!-- $Marker -->"
        ''
        'Follow the workflow defined in the canonical prompt below. Ignore tool,'
        'mode, or model names in its frontmatter; they target other AI tools.'
        ''
        'User input: $ARGUMENTS'
        ''
        "@$relSource"
    ) -join "`n"

    New-Item -ItemType Directory -Force -Path $ClaudeCommands | Out-Null
    Set-Content -Path $targetFile -Value $content -NoNewline
    $commandCount++
}

Write-Host "Generated $instructionCount instruction adapter pairs, $skillCount skill wrappers, $agentCount subagents, $commandCount commands."
if ($skippedCommands.Count -gt 0) {
    Write-Host "Prompts covered by a same-named skill (no command generated): $($skippedCommands -join ', ')."
}
