#Requires -Version 7
<#
.SYNOPSIS
    Generates Claude discovery adapters from the canonical GitHub AI assets.

.DESCRIPTION
    This repository keeps agents, prompts, instructions, collections, and skills
    under .github. This script generates thin Claude Code adapters without
    duplicating canonical content. Generated files carry a marker and may be
    safely regenerated; unmarked files are preserved.

.EXAMPLE
    pwsh -NoProfile -File ./sync_ai_assets.ps1

.OUTPUTS
    None. The script writes generated adapters beneath .claude.
#>
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$repoRoot = $PSScriptRoot
$marker = 'Generated by sync_ai_assets.ps1 - do not edit.'
$skillsRoot = Join-Path $repoRoot '.github/skills'
$instructionsRoot = Join-Path $repoRoot '.github/instructions'
$promptsRoot = Join-Path $repoRoot '.github/prompts'
$claudeSkillsRoot = Join-Path $repoRoot '.claude/skills'
$claudeRulesRoot = Join-Path $repoRoot '.claude/rules'
$claudeCommandsRoot = Join-Path $repoRoot '.claude/commands'

function Get-FrontMatter {
    param([Parameter(Mandatory)][string]$Path)

    $content = Get-Content -Raw -LiteralPath $Path
    if ($content -notmatch '(?s)^---\r?\n(?<FrontMatter>.*?)\r?\n---') {
        return $null
    }

    return $Matches.FrontMatter -replace "`r`n", "`n"
}

function Get-FrontMatterValue {
    param(
        [Parameter(Mandatory)][string]$FrontMatter,
        [Parameter(Mandatory)][string]$Name
    )

    $pattern = '(?m)^{0}:\s*[''"]?(?<Value>[^''"\r\n]+)' -f [regex]::Escape($Name)
    if ($FrontMatter -match $pattern) {
        return $Matches.Value.Trim()
    }

    return $null
}

function Remove-GeneratedFiles {
    param(
        [Parameter(Mandatory)][string]$Root,
        [Parameter(Mandatory)][string]$Filter
    )

    if (-not (Test-Path -LiteralPath $Root)) {
        return
    }

    foreach ($file in Get-ChildItem -LiteralPath $Root -Recurse -File -Filter $Filter) {
        $content = Get-Content -Raw -LiteralPath $file.FullName
        if ($content -notmatch [regex]::Escape($marker)) {
            continue
        }

        Remove-Item -LiteralPath $file.FullName -Force
        if ($file.Name -eq 'SKILL.md' -and
            -not (Get-ChildItem -LiteralPath $file.DirectoryName -Force)) {
            Remove-Item -LiteralPath $file.DirectoryName -Force
        }
    }
}

function Set-GeneratedFile {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$Content
    )

    if (Test-Path -LiteralPath $Path) {
        Write-Warning "Preserving hand-authored adapter: $Path"
        return $false
    }

    $directory = Split-Path -Parent $Path
    New-Item -ItemType Directory -Force -Path $directory | Out-Null
    Set-Content -LiteralPath $Path -Value $Content -Encoding utf8NoBOM -NoNewline
    return $true
}

Remove-GeneratedFiles -Root $claudeSkillsRoot -Filter 'SKILL.md'
Remove-GeneratedFiles -Root $claudeRulesRoot -Filter '*.md'
Remove-GeneratedFiles -Root $claudeCommandsRoot -Filter '*.md'

$skillCount = 0
foreach ($directory in Get-ChildItem -LiteralPath $skillsRoot -Directory | Sort-Object Name) {
    $source = Join-Path $directory.FullName 'SKILL.md'
    if (-not (Test-Path -LiteralPath $source)) {
        continue
    }

    $frontMatter = Get-FrontMatter -Path $source
    if (-not $frontMatter) {
        Write-Warning "Skipping skill without YAML frontmatter: $source"
        continue
    }

    $frontMatter = $frontMatter -replace '(?m)^name:\s*.*$', "name: $($directory.Name)"
    $content = @"
---
$frontMatter
---

<!-- $marker -->

Read and follow the canonical skill at ``../../../.github/skills/$($directory.Name)/SKILL.md``.
Resolve its relative references from that canonical skill directory.
"@
    $target = Join-Path $claudeSkillsRoot "$($directory.Name)/SKILL.md"
    if (Set-GeneratedFile -Path $target -Content $content) {
        $skillCount++
    }
}

$ruleCount = 0
foreach ($source in Get-ChildItem -LiteralPath $instructionsRoot -File -Filter '*.instructions.md' | Sort-Object Name) {
    $frontMatter = Get-FrontMatter -Path $source.FullName
    if (-not $frontMatter) {
        Write-Warning "Skipping instruction without YAML frontmatter: $($source.FullName)"
        continue
    }

    $description = Get-FrontMatterValue -FrontMatter $frontMatter -Name 'description'
    $applyTo = Get-FrontMatterValue -FrontMatter $frontMatter -Name 'applyTo'
    if (-not $applyTo) {
        $applyTo = '*'
    }

    $pathLines = ($applyTo -split ',' | ForEach-Object {
        $escapedPath = $_.Trim().Replace("'", "''")
        "  - '$escapedPath'"
    }) -join "`n"
    $descriptionLine = if ($description) {
        $escapedDescription = $description.Replace("'", "''")
        "description: '$escapedDescription'"
    } else {
        "description: '$($source.BaseName) repository instructions'"
    }
    $content = @"
---
$descriptionLine
paths:
$pathLines
---

<!-- $marker -->

Read and follow ``../../.github/instructions/$($source.Name)`` for files in this scope.
"@
    $slug = $source.Name -replace '\.instructions\.md$', ''
    $target = Join-Path $claudeRulesRoot "$slug.md"
    if (Set-GeneratedFile -Path $target -Content $content) {
        $ruleCount++
    }
}

$commandCount = 0
foreach ($source in Get-ChildItem -LiteralPath $promptsRoot -File -Filter '*.prompt.md' | Sort-Object Name) {
    $frontMatter = Get-FrontMatter -Path $source.FullName
    if (-not $frontMatter) {
        Write-Warning "Skipping prompt without YAML frontmatter: $($source.FullName)"
        continue
    }

    $slug = $source.Name -replace '\.prompt\.md$', ''
    $description = Get-FrontMatterValue -FrontMatter $frontMatter -Name 'description'
    if (-not $description) {
        $description = "Run the $slug workflow."
    }
    $escapedDescription = $description.Replace("'", "''")
    $content = @"
---
description: '$escapedDescription'
---

<!-- $marker -->

Read and execute the canonical prompt at ``../../.github/prompts/$($source.Name)`` using the user's arguments as its input.
"@
    $target = Join-Path $claudeCommandsRoot "$slug.md"
    if (Set-GeneratedFile -Path $target -Content $content) {
        $commandCount++
    }
}

Write-Host "Generated $skillCount Claude skill adapters, $ruleCount rules, and $commandCount commands."
