from __future__ import annotations

import re
import unittest
from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
GENERATION_MARKER = "Generated by sync_ai_assets.ps1"


def read_frontmatter(path: Path) -> list[str]:
    content = path.read_text(encoding="utf-8-sig")
    match = re.match(r"^---\r?\n(.*?)\r?\n---(?:\r?\n|$)", content, re.DOTALL)
    if match is None:
        raise AssertionError(f"{path.relative_to(REPOSITORY_ROOT)} has no YAML frontmatter")
    return match.group(1).splitlines()


def scalar_value(lines: list[str], field: str) -> str | None:
    prefix = f"{field}:"
    for line in lines:
        if line.startswith(prefix):
            value = line.removeprefix(prefix).strip().strip("'\"")
            return value or None
    return None


class CanonicalAiAssetTests(unittest.TestCase):
    def test_shared_skills_have_matching_names_and_descriptions(self) -> None:
        skills_root = REPOSITORY_ROOT / ".agents" / "skills"
        for skill_directory in sorted(path for path in skills_root.iterdir() if path.is_dir()):
            with self.subTest(skill=skill_directory.name):
                self.assertRegex(skill_directory.name, r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
                skill_file = skill_directory / "SKILL.md"
                self.assertTrue(skill_file.is_file(), f"Missing {skill_file}")
                frontmatter = read_frontmatter(skill_file)
                self.assertEqual(skill_directory.name, scalar_value(frontmatter, "name"))
                self.assertTrue(
                    any(line.startswith("description:") for line in frontmatter),
                    f"{skill_file} has no description",
                )

    def test_agents_and_prompts_have_required_metadata(self) -> None:
        cases = (
            (REPOSITORY_ROOT / ".ai" / "agents", ".agent.md", ("name", "description")),
            (REPOSITORY_ROOT / ".ai" / "prompts", ".prompt.md", ("description",)),
        )
        for root, required_suffix, required_fields in cases:
            for path in sorted(candidate for candidate in root.iterdir() if candidate.is_file()):
                with self.subTest(asset=path.name):
                    self.assertTrue(path.name.endswith(required_suffix), f"Unexpected asset name {path}")
                    frontmatter = read_frontmatter(path)
                    for field in required_fields:
                        self.assertTrue(
                            any(line.startswith(f"{field}:") for line in frontmatter),
                            f"{path} has no {field}",
                        )

    def test_instructions_have_paths_and_matching_generated_adapters(self) -> None:
        instructions_root = REPOSITORY_ROOT / ".ai" / "instructions"
        for instruction in sorted(instructions_root.glob("*.md")):
            with self.subTest(instruction=instruction.name):
                frontmatter = read_frontmatter(instruction)
                self.assertTrue(any(line.startswith("description:") for line in frontmatter))
                self.assertIn("paths:", frontmatter)
                self.assertTrue(any(re.match(r"^\s+-\s+\S", line) for line in frontmatter))

                slug = instruction.stem
                generated_files = (
                    REPOSITORY_ROOT / ".github" / "instructions" / f"{slug}.instructions.md",
                    REPOSITORY_ROOT / ".claude" / "rules" / f"{slug}.md",
                )
                for generated_file in generated_files:
                    self.assertTrue(generated_file.is_file(), f"Missing {generated_file}")
                    self.assertIn(
                        GENERATION_MARKER,
                        generated_file.read_text(encoding="utf-8-sig"),
                    )

    def test_shared_skills_have_generated_claude_wrappers(self) -> None:
        skills_root = REPOSITORY_ROOT / ".agents" / "skills"
        expected_wrappers: set[str] = set()
        for skill_directory in sorted(path for path in skills_root.iterdir() if path.is_dir()):
            with self.subTest(skill=skill_directory.name):
                expected_wrappers.add(skill_directory.name)
                wrapper = REPOSITORY_ROOT / ".claude" / "skills" / skill_directory.name / "SKILL.md"
                self.assertTrue(wrapper.is_file(), f"Missing {wrapper}")
                self.assertIn(GENERATION_MARKER, wrapper.read_text(encoding="utf-8-sig"))

        generated_wrappers = {
            path.parent.name
            for path in (REPOSITORY_ROOT / ".claude" / "skills").glob("*/SKILL.md")
            if GENERATION_MARKER in path.read_text(encoding="utf-8-sig")
        }
        self.assertEqual(expected_wrappers, generated_wrappers)

    def test_prompts_have_unambiguous_claude_discovery(self) -> None:
        shared_skills = {
            path.name
            for path in (REPOSITORY_ROOT / ".agents" / "skills").iterdir()
            if path.is_dir()
        }
        commands_root = REPOSITORY_ROOT / ".claude" / "commands"
        expected_commands: set[str] = set()
        for prompt in (REPOSITORY_ROOT / ".ai" / "prompts").glob("*.prompt.md"):
            slug = prompt.name.removesuffix(".prompt.md").lower()
            command = commands_root / f"{slug}.md"
            if slug in shared_skills:
                self.assertFalse(command.exists(), f"Ambiguous skill and command named {slug}")
            else:
                expected_commands.add(slug)
                self.assertTrue(command.is_file(), f"Missing {command}")
                self.assertIn(GENERATION_MARKER, command.read_text(encoding="utf-8-sig"))

        generated_commands = {
            path.stem
            for path in commands_root.glob("*.md")
            if GENERATION_MARKER in path.read_text(encoding="utf-8-sig")
        }
        self.assertEqual(expected_commands, generated_commands)

    def test_collection_pairs_and_item_paths_resolve(self) -> None:
        collections_root = REPOSITORY_ROOT / ".ai" / "collections"
        for manifest in sorted(collections_root.glob("*.collection.yml")):
            with self.subTest(collection=manifest.name):
                documentation = manifest.with_name(manifest.name.replace(".collection.yml", ".md"))
                self.assertTrue(documentation.is_file(), f"Missing {documentation}")
                for relative_path in re.findall(
                    r"^\s*-\s+path:\s*['\"]?([^'\"\s]+)",
                    manifest.read_text(encoding="utf-8-sig"),
                    re.MULTILINE,
                ):
                    target = REPOSITORY_ROOT / ".ai" / relative_path
                    self.assertTrue(target.is_file(), f"Missing collection item {target}")


if __name__ == "__main__":
    unittest.main()
