name: "Copilot Setup Steps"

on:
    workflow_dispatch:
    push:
        paths:
            - .github/workflows/copilot-setup-steps.yml
    pull_request:
        paths:
            - .github/workflows/copilot-setup-steps.yml

permissions:
    id-token: write
    contents: read

jobs:
    copilot-setup-steps:
        name: Copilot Configuration
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - uses: actions/setup-dotnet@v5
              with:
                dotnet-version: |
                    10.x

            - name: Set up JFrog CLI
              uses: jfrog/setup-jfrog-cli@v4
              env:
                JF_URL: https://icseng.jfrog.io
              with:
                oidc-provider-name: jfrog

            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                node-version: '24'

            - name: Configure & install JavaScript dependencies
              working-directory: src/Edu.Si.Example/Edu.Si.Example.Client
              run: |
                jf npm-config --repo-resolve npm-ics
                jf npm ci

            - name: Configure & restore dotnet dependencies
              run: |
                jf dotnet-config --repo-resolve nuget
                dotnet restore Edu.Si.Example.sln
